<?php
require_once "configuration.php";
header("Access-Control-Allow-Headers: *");
header("Access-Control-Allow-Origin: *");
$postdata = file_get_contents("php://input");
$request = json_decode($postdata);
$id = $request->id;
$brand = $request->brand;
$model = $request->model;
$year = $request->year;
$mileage = $request->mileage;
$price = $request->price;
$condition = $request->condition;
$transmission = $request->transmission;
$fuel_type = $request->fuel_type;
$engine_size = $request->engine_size;
$fuel_efficiency = $request->fuel_efficiency;
$color = $request->color;
$sql_query = "update `car` set brand = '$brand', model = '$model', year = '$year', mileage = '$mileage', price = '$price', `condition` = '$condition', transmission = '$transmission', fuel_type = '$fuel_type', engine_size = '$engine_size', fuel_efficiency = '$fuel_efficiency', color = '$color' where id = $id;";
global $connection;
$result = mysqli_query($connection, $sql_query);
echo "Your car was updated successfully!";
mysqli_close($connection);